import Head from "next/head";
import { Layout, Button } from "components";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Amazing smiles</h1>
      <h1>Fair prices</h1>
      <h2>No compromise on quality</h2>
      <Button>GET A QUOTE</Button>
    </Layout>
  );
}
