import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import Head from "next/head";
import styles from "./index.module.scss";
import { Layout, Button, Box, Mouth } from "components";
import { useEffect, useState, Suspense } from "react";

export default function Home() {
  const [card, setCard] = useState(false);
  const toggleCard = () => {
    setCard(!card);
  };
  const [mounted, setMounted] = useState();
  useEffect(() => {
    setMounted(true);
  }, []);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Amazing smiles</h1>
      <h1>Fair prices</h1>
      <h2>No compromise on quality</h2>
      <Button>GET A QUOTE</Button>
      <div className={styles.boxesContainer}>
        <Canvas>
          <ambientLight />
          <pointLight position={[5, 5, 5]} />
          <Box position={[0, 0, 0]} toggleCard={toggleCard} />
          <OrbitControls />
        </Canvas>
        <Canvas>
          <ambientLight />
          <pointLight position={[5, 5, 5]} />
          <Box position={[0, 0, 0]} toggleCard={toggleCard} />
          <OrbitControls />
        </Canvas>
        {mounted && (
          <Canvas
            orthographic
            camera={{ zoom: 20 }}
          >
            <Suspense fallback={null}>
              <ambientLight intensity={0.7} />
              <Mouth />
							<OrbitControls />
            </Suspense>
          </Canvas>
        )}
      </div>
      {card && <h1>card toggled</h1>}
    </Layout>
  );
}
